### PR TITLE
Removed a element

### PR DESCRIPTION
**Pull request by AnuragNishad12**
image

### CODE REVIEW

**Comment by LianaHus** [comment]
i don't see this element. What should I do to reproduce this?

**Comment by Aniket-Engg** [comment]
> i don't see this element. What should I do to reproduce this?

you need to right click on search plugin icon

**Comment by LianaHus** [comment]
ok the issue is search plugin has no documentation URL in it's profile @Aniket-Engg

**Comment by Aniket-Engg** [comment]
Fixed by #3991

**Pull request closed without merging**
