### PR TITLE
files can now be dragged and drop

### PR DESCRIPTION
**Pull request by iamsethsamuel**
This enables the ability of files and folders to be dragged and dropped in folders. This will solve 6 opened issues

### CODE REVIEW

**Review by iamsethsamuel — COMMENTED** [review]
I have redesigned the drag to work as a library

**Review by iamsethsamuel — COMMENTED** [review]
drag and drop is now a library

**Comment by iamsethsamuel** [comment]
Please help me fix the remix-libs test

**Comment by ioedeveloper** [comment]
@iamsethsamuel Resolve merge conflicts

**Comment by iamsethsamuel** [comment]
Okay sir

**Review by ioedeveloper — APPROVED** [review]

**Comment by Aniket-Engg** [comment]
@iamsethsamuel Can you fix linting issue and rebase PR?

**Comment by joeizang** [comment]
Meets and satisfies all e2e tests.

**Review by joeizang — APPROVED** [review]

**Pull request merged**
