### PR TITLE
Hometab: Learneth slider & Learneth promo

### PR DESCRIPTION
**Pull request by ryestew**
The code needs to be organized better.  The cursor needs to be an pointer in the slider.

### CODE REVIEW

**Comment by LianaHus** [comment]
Please change the image before merge

**Review by joeizang — CHANGES_REQUESTED** [review]
fix e2e's and the pr is golden.

**Review by joeizang — APPROVED** [review]

**Review by bunsenstraat — DISMISSED** [review]
no need to include list.json
you can run
git checkout master -- apps/remix-ide/src/assets/list.json 
then add the change commit push

**Comment by vermouth22** [comment]
The image could be a lot larger... like it is for Beta Tester panel. Also, the cursor is still showing on rollover of "Start Learning" button instead of a pointer

**Comment by Aniket-Engg** [comment]
> no need to include list.json you can run git checkout master -- apps/remix-ide/src/assets/list.json then add the change commit push

list.json removed

**Comment by Aniket-Engg** [comment]
> The image could be a lot larger... like it is for Beta Tester panel. Also, the cursor is still showing on rollover of "Start Learning" button instead of a pointer

Image looks quite similar to one in beta tester panel. I update the cursor to pointer too

**Review by Aniket-Engg — APPROVED** [review]

**Pull request merged**
