### PR TITLE
enable contract pinning for VM

### PR DESCRIPTION
**Pull request by Aniket-Engg**
Allow to pin contract for VM environments

### CODE REVIEW

**Comment by LianaHus** [comment]
pinned btn is still green instead of filled

**Comment by LianaHus** [comment]
you need a bit more space after "Currently you have no pinned contracts to interact with.", also once you pin and unpit a contract you don't see that msg anymore. The other issue is that one and the one for unpinned have different styles. can't we make the similar? for example text-secondary or text-info.

**Comment by yann300** [comment]
can we add (if it's not arleady there) a matomo check when one interact with a pinned instance.

**Comment by LianaHus** [comment]
data-id deployAndRunClearInstances  p-2
data-id NoPinnedInstanceText  m-2
no item elements: alert alert-secondary

**Comment by Aniket-Engg** [comment]
> secondary

done

**Comment by Aniket-Engg** [comment]
> you need a bit more space after "Currently you have no pinned contracts to interact with.", also once you pin and unpit a contract you don't see that msg anymore. The other issue is that one and the one for unpinned have different styles. can't we make the similar? for example text-secondary or text-info.

done

**Comment by Aniket-Engg** [comment]
> pinned btn is still green instead of filled

done

**Comment by Aniket-Engg** [comment]
> can we add (if it's not arleady there) a matomo check when one interact with a pinned instance.

done

**Comment by LianaHus** [comment]
with the way you log in matomo we can't filter by network. I would like to know why @yann300 want to add tracking and what exactly should be tracked.

**Comment by Aniket-Engg** [comment]
> with the way you log in matomo we can't filter by network. I would like to know why @yann300 want to add tracking and what exactly should be tracked.

If purpose of adding matomo is to ensure that user interact with pinned contract, that is solved by matomo added in this PR.

There is already a matomo tracking which checks on which network contract is pinned

**Pull request merged**
