### PR TITLE
Semaphore template

### PR DESCRIPTION
**Pull request by ioedeveloper**

### CODE REVIEW

**Comment by yann300** [comment]
When a semaphore template is being created, probably we should activate the circom plugin.

**Comment by bunsenstraat** [comment]
> When a semaphore template is being created, probably we should activate the circom plugin.

In the PR the circuit plugin doesn't load right? is that correct?

**Comment by yann300** [comment]
> > When a semaphore template is being created, probably we should activate the circom plugin.
> 
> In the PR the circuit plugin doesn't load right? is that correct?

In this PR I don't think so, it probably should

**Comment by ioedeveloper** [comment]
> > When a semaphore template is being created, probably we should activate the circom plugin.
> 
> In the PR the circuit plugin doesn't load right? is that correct?

In this PR, the circuit-compiler UI is not present, it only contains semaphore template. This PR has the changes for circuit-compiler UI https://github.com/ethereum/remix-project/pull/4144

**Comment by yann300** [comment]
> > > When a semaphore template is being created, probably we should activate the circom plugin.
> > 
> > 
> > In the PR the circuit plugin doesn't load right? is that correct?
> 
> In this PR, the circuit-compiler UI is not present, it only contains semaphore template. This PR has the changes for circuit-compiler UI #4144

ok so let's do it in an another PR..

**Review by yann300 — APPROVED** [review]

**Pull request merged**
