### PR TITLE
Add language

### PR DESCRIPTION
**Pull request by ShenWe0x**
Add Turkish language

### CODE REVIEW

**Comment by Aniket-Engg** [comment]
@ShenWe0x Build is failing

**Comment by ShenWe0x** [comment]
@Aniket-Engg  I fixed the problem, can you compile it again?

**Comment by ryestew** [comment]
Thanks @ShenWe0x  for this PR - I am sorry but we need to manage languages in our translation management platform.  I really appreciate the work you have done, but the translations need to be input here:
https://crowdin.com/project/remix-ui/tr

So I need to close this PR.

**Comment by ryestew** [comment]
@ShenWe0x - see the comment above.

**Pull request closed without merging**
