### PR TITLE
Some style improvements on home tab

### PR DESCRIPTION
**Pull request by LianaHus**
fix https://github.com/ethereum/remix-project/issues/3220
- Replaced the logo
- improved size changes of Featured section for Zoom in/out
- Featured section has smaller btns/links now
- Learneth has smaller text
- added tooltips

### CODE REVIEW

**Comment by Aniket-Engg** [comment]
Screenshot 2023-02-09 at 5 05 18 PM

Looks like this to me

**Review by Aniket-Engg — COMMENTED** [review]
Not sure if we should add tooltip to  `New File` and `Open File` too

**Review by Aniket-Engg — COMMENTED** [review]
Font size of `Get Started- Project Templates` can be a bit minimized.

**Comment by LianaHus** [comment]
> Not sure if we should add tooltip to `New File` and `Open File` too

it is pretty obvious, I don't think we need to explain "new file" action

**Review by Aniket-Engg — APPROVED** [review]
LGTM!

**Pull request merged**
