### PR TITLE
Publish files and folder to gist

### PR DESCRIPTION
**Pull request by ioedeveloper**
Fixes https://github.com/ethereum/remix-project/issues/850

### CODE REVIEW

**Comment by bunsenstraat** [comment]
If I  type in a file, and then not trigger the save action, for example by switching files or whatever but directly click on publish to gist it will publish the old content. So maybe save first then gist?

**Comment by yann300** [comment]
It seems that the filename should be sanitized when importing a gist:

 - publish a file
 - in gist, the title looks like `yann300/3_Ballot.sol`
 - I re-import it from the home page, in the tab, the file name appears as `gist-<id>/<filename>`
 - when I push the changes to gist, the title is now `yann300/gist-0c5b0ed330a050e7a3f958cd83e04ba9...3_Ballot.sol`

**Review by yann300 — APPROVED** [review]

**Comment by ioedeveloper** [comment]
> this will only replace the first occurrence of `...` .
> try `test.replace(/\.\.\./g, '/')`

Yes, thanks.

**Comment by yann300** [comment]
I just tried https://github.com/ethereum/remix-project/pull/1185/commits/ec52d92d7b4aa3845ce7260d0feb0f0829318bfa this works well

**Pull request merged**
