### PR TITLE
Check for github action updates monthly

### PR DESCRIPTION
**Pull request by jlosito**
This will use dependabot to check any of the github actions that this project uses for updates and submit pull requests with version bumps.

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

### CODE REVIEW

**Comment by jlosito** [comment]
@ioedeveloper Out of curiosity, was there any reason why this was closed? Should something be changed?

**Comment by ioedeveloper** [comment]
@jlosito I closed the PR because i couldn't see the importance of the PR to the project and also i couldn't find the testing instructions for the PR.

**Comment by jlosito** [comment]
How is this project keeping its dependencies up-to-date then if not by dependabot or by some other means like renovate?

**Comment by jlosito** [comment]
How is this project keeping its dependencies up-to-date then if not by dependabot or by some other means like renovate?

**Pull request closed without merging**
