### PR TITLE
unknown icon form plugin without a logo

### PR DESCRIPTION
**Pull request by LianaHus**
fixing https://github.com/ethereum/remix-project/issues/3466
fixing https://github.com/ethereum/remix-project/issues/3772

### CODE REVIEW

**Review by Aniket-Engg — COMMENTED** [review]
I am not sure if question mark icon is the right choice for this. May be use plug-in icon instead

**Comment by LianaHus** [comment]
> I am not sure if question mark icon is the right choice for this. May be use plug-in icon instead

ok, Can you check again? @Aniket-Engg

**Review by joeizang — COMMENTED** [review]
The broken icon is fixed  and shows correctly. But the UMA icon is now broken. See image below
image

**Comment by Aniket-Engg** [comment]
Screenshot 2023-12-19 at 2 50 02 PM

@joeizang It looks fine to me

**Review by joeizang — APPROVED** [review]

**Pull request merged**
