### PR TITLE
Fixed settings tab

### PR DESCRIPTION
**Pull request by ioedeveloper**
Fixes https://github.com/ethereum/remix-project/issues/1349

### CODE REVIEW

**Comment by bunsenstraat** [comment]
Clear the localstorage in icognito and reload:
- no modal anymore
- an error in console
-
Screenshot 2021-07-06 at 12 57 28

**Comment by ioedeveloper** [comment]
> Clear the localstorage in icognito and reload:
> 
>     * no modal anymore
> 
>     * an error in console
> 
> 
> Screenshot 2021-07-06 at 12 57 28

The modal is only expected to show for matomo track urls (alpha, beta and live). It should work after merge. Or you can test it by disabling the url check locally.

**Comment by bunsenstraat** [comment]
Ok I disabled url check:
- clear storage 
- load icognito
- the warning still appears
- click 'sure', the settings is updated,
- but on reload it keeps showing me the modal also if I decline

**Review by tizah — APPROVED** [review]
Looks good,

**Pull request merged**
