### PR TITLE
Ensure injected provider present

### PR DESCRIPTION
**Pull request by yann300**
fix https://github.com/ethereum/remix-project/issues/3044

### CODE REVIEW

**Review by Aniket-Engg — COMMENTED** [review]
Screenshot 2022-10-26 at 7 55 36 PM

It shows a toaster and keep the L2 provider selected. It can be better to do it same as we do for `Injected Provider`

**Review by Aniket-Engg — COMMENTED** [review]
Not sure if it is only for me but the warning toaster is only shown once on selecting any L2 or injected provider

**Comment by bunsenstraat** [comment]
> Not sure if it is only for me but the warning toaster is only shown once on selecting any L2 or injected provider

The issue is the toaster, not this PR. the toaster system gets the message as a state string. When the message is identical to the previous it won't update state so won't show the toaster. Best thing is to make another PR to change toaster behaviour. needs discussion @Aniket-Engg

**Review by bunsenstraat — APPROVED** [review]

**Comment by Aniket-Engg** [comment]
> > Not sure if it is only for me but the warning toaster is only shown once on selecting any L2 or injected provider
> 
> The issue is the toaster, not this PR. the toaster system gets the message as a state string. When the message is identical to the previous it won't update state so won't show the toaster. Best thing is to make another PR to change toaster behaviour. needs discussion @Aniket-Engg

will be tracked in https://github.com/ethereum/remix-project/issues/3060

**Review by Aniket-Engg — APPROVED** [review]

**Pull request merged**
