### PR TITLE
Translation to Farsi

### PR DESCRIPTION
**Pull request by saremeskandary**
Farsi translations added based on the `CONTRIBUTING.md`
please consider that Farsi need RTL support like Arabic.

### CODE REVIEW

**Comment by ryestew** [comment]
@saremeskandary - thanks so much for your work and your contribution.  We at Remix appreciate it so much.  Unfortunately, the file CONTRIBUTING.md is not clear for translation contributions.  It needs editing  ASAP.  I'll take care of that.  I'm ashamed that its lack of clarity lead you to do some work that we need in another format.  

Translations are managed through our translation management platform: https://crowdin.com/project/remix-ui and the Farsi section is here: https://crowdin.com/project/remix-ui/fa

If you could put your translations there, I can get merged into Remix quite soon.

**Comment by saremeskandary** [comment]
Ok. How can I get notified when it's ready?
Do you have telegram or discord?

**Comment by ryestew** [comment]
Send me an email at remix@ethereum.org or join the Remix discord:  https://discord.gg/YDVgA95d and

**Comment by ryestew** [comment]
@saremeskandary - please do get in touch.  Thanks

**Pull request closed without merging**
