### PR TITLE
Ctrl + Z undos last file action

### PR DESCRIPTION
**Pull request by iamsethsamuel**

### CODE REVIEW

**Comment by iamsethsamuel** [comment]
> Hi @iamsethsamuel. I know it's been a very very very very long time. But I'd like to put your PR changes into the main repo. However I'd like to do some changes to it which I can execute if you're ok with that:
> 
> * the key press should be linked to editor:
> * if you are editing the file and the undo buffer in the editor must run out first before you can undo a rename or a move, basically editing blocks the file undo. will have to look at the editor api for that.
> * the ctrl z zone is global, so not on the file explorer alone, the editor should fire the event most of the time and when the buffer runs out we do the action of the undo
> * when file changes happen outside of direct action of a user, ie a git pull etc, or when the compiler creates a file and so on it should clear the undo action possibility. basically the undo is only undoing the last **_manual_** action a user did. To achieve this the actions need to record the origin.
> * A modal should appear asking to confirm the undo action
> * We need to write e2e tests for it :)
> 
> If we do that we can soon merge this. I propose I merge this PR into a new branch on our repo and take it from there.
> 
> Thanks for helping out!

Okay, I will you work on the changes or....

**Comment by bunsenstraat** [comment]
@iamsethsamuel Yes I'll do it. It requires some meddling with the monaco editor. That's a bit of puzzle.

**Comment by iamsethsamuel** [comment]
> > Hi @iamsethsamuel. I know it's been a very very very very long time. But I'd like to put your PR changes into the main repo. However I'd like to do some changes to it which I can execute if you're ok with that:
> > 
> > * the key press should be linked to editor:
> > * if you are editing the file and the undo buffer in the editor must run out first before you can undo a rename or a move, basically editing blocks the file undo. will have to look at the editor api for that.
> > * the ctrl z zone is global, so not on the file explorer alone, the editor should fire the event most of the time and when the buffer runs out we do the action of the undo
> > * when file changes happen outside of direct action of a user, ie a git pull etc, or when the compiler creates a file and so on it should clear the undo action possibility. basically the undo is only undoing the last **_manual_** action a user did. To achieve this the actions need to record the origin.
> > * A modal should appear asking to confirm the undo action
> > * We need to write e2e tests for it :)
> > 
> > If we do that we can soon merge this. I propose I merge this PR into a new branch on our repo and take it from there.
> > Thanks for helping out!
> 
> Okay, I will you work on the changes or....

Please let me know how I can help

**Comment by bunsenstraat** [comment]
> > > Hi @iamsethsamuel. I know it's been a very very very very long time. But I'd like to put your PR changes into the main repo. However I'd like to do some changes to it which I can execute if you're ok with that:
> > > 
> > > * the key press should be linked to editor:
> > > * if you are editing the file and the undo buffer in the editor must run out first before you can undo a rename or a move, basically editing blocks the file undo. will have to look at the editor api for that.
> > > * the ctrl z zone is global, so not on the file explorer alone, the editor should fire the event most of the time and when the buffer runs out we do the action of the undo
> > > * when file changes happen outside of direct action of a user, ie a git pull etc, or when the compiler creates a file and so on it should clear the undo action possibility. basically the undo is only undoing the last **_manual_** action a user did. To achieve this the actions need to record the origin.
> > > * A modal should appear asking to confirm the undo action
> > > * We need to write e2e tests for it :)
> > > 
> > > If we do that we can soon merge this. I propose I merge this PR into a new branch on our repo and take it from there.
> > > Thanks for helping out!
> > 
> > 
> > Okay, I will you work on the changes or....
> 
> Please let me know how I can help

after we let you wait for a million years with this very good idea I'm not going to ask anything :) that would be unfair to you.

**Comment by yann300** [comment]
@iamsethsamuel 
I gonna close the PR now, cause this been quite some time. Thanks very much for your patience, perhaps @bunsenstraat can dig it more when he will have some more time.

**Pull request closed without merging**
