### PR TITLE
Updated default to 0.8.4 also the local one

### PR DESCRIPTION
**Pull request by LianaHus**

### CODE REVIEW

**Comment by yann300** [comment]
selection "default local version" triggers this error:
```
Uncaught TypeError: Invalid Version: 
    at new SemVer (/ipfs/QmTUKYWR7vqHTeMbgBStA1P52s8ehUgKNb9jpNE7Rd692J/vendor.js:345546)
    at compare (/ipfs/QmTUKYWR7vqHTeMbgBStA1P52s8ehUgKNb9jpNE7Rd692J/vendor.js:345861)
    at Function.lt (/ipfs/QmTUKYWR7vqHTeMbgBStA1P52s8ehUgKNb9jpNE7Rd692J/vendor.js:345902)
    at CompilerContainer._updateVersionSelector (/ipfs/QmTUKYWR7vqHTeMbgBStA1P52s8ehUgKNb9jpNE7Rd692J/main.js:42624)
    at CompilerContainer.oncha
```
A fix should probably be put in this PR or at least in the release.

**Comment by LianaHus** [comment]
> selecting "default local version" triggers this error:
> 
> ```
> Uncaught TypeError: Invalid Version: 
>     at new SemVer (/ipfs/QmTUKYWR7vqHTeMbgBStA1P52s8ehUgKNb9jpNE7Rd692J/vendor.js:345546)
>     at compare (/ipfs/QmTUKYWR7vqHTeMbgBStA1P52s8ehUgKNb9jpNE7Rd692J/vendor.js:345861)
>     at Function.lt (/ipfs/QmTUKYWR7vqHTeMbgBStA1P52s8ehUgKNb9jpNE7Rd692J/vendor.js:345902)
>     at CompilerContainer._updateVersionSelector (/ipfs/QmTUKYWR7vqHTeMbgBStA1P52s8ehUgKNb9jpNE7Rd692J/main.js:42624)
>     at CompilerContainer.oncha
> ```
> 
> A fix should probably be put in this PR or at least in the release.

semver is checking the key to retrieve a version. in this case the key was set to 'builtin'. this should be refactor a bit or builtin should be ignored by pragma.

**Comment by yann300** [comment]
> builtin should be ignored by pragma.

if `builtin` can't we easily see what is the actual version? I think that is hard coded somewhere no?

**Comment by LianaHus** [comment]
> > builtin should be ignored by pragma.
> 
> if `builtin` can't we easily see what is the actual version? I think that is hardcoded somewhere no?

it is hardcoded in different places.

> > builtin should be ignored by pragma.
> 
> if `builtin` can't we easily see what is the actual version? I think that is hard coded somewhere no?

sure we can. I'll push this fix in another PR

**Review by yann300 — APPROVED** [review]

**Pull request merged**
