### PR TITLE
add custom endpoint for AI suggestion

### PR DESCRIPTION
**Pull request by yann300**
create a script in Remix:
like
```
(async () => {
  try {
    remix.call('copilot-suggestion' as any, 'useRemoteService', 'http://replit.remixcompletion.pro/infer')
    console.log('done')
  } catch (e) {
    console.log(e.message)
  }
})()
```
and run it to use a remote endpoint instead of the in-browser model.

### CODE REVIEW

**Comment by STetsing** [comment]
@yann300  where am I supposed to execute that JS?

**Comment by yann300** [comment]
@STetsing you have to run it from Remix.

**Review by STetsing — COMMENTED** [review]
The results is not displayed in the editor, Increasing the request timeout (if existent) could help

**Comment by STetsing** [comment]
> > * The replit endpoints works well
> > * the starcoder endpoint ends up with a `   Failed to load resource: net::ERR_FAILED starcoder.remixcompletion.pro/infer`
> 
> the second issue looks like a server issue, is this the case?

no, the server returns a payload indeed, what is the request max timeout? the min inference time for starcoder ti max_new_word=5 is 6-5 seconds (mean value).

**Comment by yann300** [comment]
> what is the request max timeout

I think this can be configured by passing some options to https://github.com/ethereum/remix-project/pull/4319/files#diff-456892ab56ea0fe769bc1bdb2c0ece2855f1ce80583e2309939106e9cf727f0eR68 but I don't know the default value..

**Comment by STetsing** [comment]
The endpoints works well after reducing the max number of tokens (especially for the starcoder model). The timeout value must be increased for large generation requests

**Review by STetsing — APPROVED** [review]
Working as Is

**Pull request merged**
