### PR TITLE
terminal dragbar zindex reduced

### PR DESCRIPTION
**Pull request by iamsethsamuel**
I noticed the dragbar is showing on top of the AIChat window. So I reduced the zIndex of the dragbar. 

image

### CODE REVIEW

**Review by LianaHus — APPROVED** [review]

**Comment by LianaHus** [comment]
thanks for the PR @iamsethsamuel

**Comment by iamsethsamuel** [comment]
> thanks for the PR @iamsethsamuel

Thank you for approving

**Comment by iamsethsamuel** [comment]
This tests failing has nothing to do with my code? I don't know if this can be auto merged 
image

**Comment by LianaHus** [comment]
no it hasn't. I merged :)

**Pull request merged**
