### PR TITLE
Fix vertical icons scroll

### PR DESCRIPTION
**Pull request by joeizang**

### CODE REVIEW

**Comment by yann300** [comment]
could you rebase?

**Comment by joeizang** [comment]
> could you rebase?

I will do that. Sorry for the delay
\

**Comment by yann300** [comment]
is the fix that the scroll doesn't work at all? can you provide some info for testing it?

**Comment by joeizang** [comment]
> is the fix that the scroll doesn't work at all? can you provide some info for testing it?

No scroll works, but scroll behaviour seems inconsistent on mac as tested by @ryestew. And @bunsenstraat asked for chevrons to be displayed on scrolling behaviour activation and also on window resize. I am working to make that dependent on react state using a reducer.

**Comment by yann300** [comment]
@joeizang any update on this? is this ready for review?

**Comment by joeizang** [comment]
> @joeizang any update on this? is this ready for review?

Yes @yann300, it is ready for review. Will inform @bunsenstraat, @ryestew & @LianaHus to give it a look

**Review by bunsenstraat — APPROVED** [review]

**Pull request merged**
