### PR TITLE
Pride theme improvements. Fixing the text on the btns on d&r

### PR DESCRIPTION
**Pull request by LianaHus**
- fixing some color problems in Pride theme. 
- Fixing the btns text on deploy and run

### CODE REVIEW

**Comment by joeizang** [comment]
image

The button in the debugger requires a bit of work on contrast.

**Comment by LianaHus** [comment]
the border is thiner now. The btns are meant to have some colors, this is different from the light theme, but that color is not enough for white.

**Comment by Aniket-Engg** [comment]
> image
> 
> The active state of the buttons need a bit of work with contrast. Black text on these buttons really don't work.

I agree on this. Color contrast should be improved

**Review by joeizang — APPROVED** [review]

**Comment by B-Venkatesh7210** [comment]
How can I reject this PR?

**Comment by yann300** [comment]
@B-Venkatesh7210 
As it's already approved, it will most probably be merged. 
If you want more improvements to be done regarding the theming part, please feel free to create an issue. We also welcome any external contribution ofc.

**Comment by LianaHus** [comment]
updated @Aniket-Engg @joeizang

**Review by Aniket-Engg — APPROVED** [review]

**Pull request merged**
