### PR TITLE
Add SKALE Chaos Testnet Injected Provider

### PR DESCRIPTION
**Pull request by TheGreatAxios**
- Adds greater support for SKALE Networks Chaos Testnet chain 
- This chain has no permissions meaning that anyone can deploy to it without needing to be provided access
- The only requirement is the gas token sFUEL which is free to attain at: https://sfuel.dirtroad.dev/staging/chaos or https://sfuel.skalenetwork/staging/chaos

### CODE REVIEW

**Comment by payvint** [comment]
Good idea!

I would like to see more testnets in Remix, especially SKALE!

**Comment by TheGreatAxios** [comment]
Hey team -- 

Checking in here to see if this is updated if it would be merged?
Never recieved any feedback and would like to have this available to developers. 

Thanks

**Comment by yann300** [comment]
hello @TheGreatAxios sorry for the delay, could you rebase the PR (we renamed one of the class), it will go in the next release.
We are also going to improve the UI for this dropdown so if you have other testnet to put in, feel free to do it.
Thanks ;)

**Comment by TheGreatAxios** [comment]
Hey @yann300 

Yes, will try and get to this tomorrow. 
If anyone on your team has the bandwidth to quickly make the changes please feel free to resolve issues and push up and merge in. 

Thank you!

**Pull request closed without merging**
