### PR TITLE
Updated contributions

### PR DESCRIPTION
**Pull request by iamsethsamuel**
This is to fix the history and update my contributions with the correct email address.

### CODE REVIEW

**Comment by iamsethsamuel** [comment]
I got it from GitHub support page. Please help me merge so that my contributions can come back 
Screenshot 2024-11-04 at 11 17 44

**Comment by LianaHus** [comment]
this doesn't look correct. you have more commits than you need for this pr. please rebase over master

**Comment by iamsethsamuel** [comment]
> this doesn't look correct. you have more commits than you need for this pr. please rebase over master

I just corrected the commit history with my correct email address. I didn't change anything

**Comment by iamsethsamuel** [comment]
> this doesn't look correct. you have more commits than you need for this pr. please rebase over master

Screenshot 2024-11-06 at 08 58 08
I have rebased ma

**Pull request closed without merging**
