### PR TITLE
ui bug fixed

### PR DESCRIPTION
**Pull request by ijlal321**
### Hi, there was a text overlap in run tab section. Here is before and after.

Screenshot 2024-08-17 222825

After changing line Height

image

## Note: Text overlap only happens when there is a contract deployed.

Let me know if need any further details or changes. Thanks

### CODE REVIEW

**Review by joeizang — CHANGES_REQUESTED** [review]
Nice try. But you cannot make changes to the theme css file. That's like editing a bootstrap.min.css file. Can you find a better way?

**Comment by ijlal321** [comment]
> Nice try. But you cannot make changes to the theme css file. That's like editing a bootstrap.min.css file. Can you find a better way?

Thanks for clarification @joeizang. I have updated code.
let me know if you need anything else 👍

**Review by joeizang — CHANGES_REQUESTED** [review]
Much better. But I think there should be a bootstrap class that can do this.

**Comment by ijlal321** [comment]
Hi @joeizang. 
So there is no way of doing this using Bootstrap, because I believe remix uses custom theme CSS files which are from Bootstrap4. 

lh (line height class need to fix this bug) was introduced in bootstrap5.

Ofc we can make changes to theme css files to include lh class,  but i think my last approach using CSS selector is much better.

Also I am new to all this, so I am extremely grateful for all the guidance you have provided in last messages. Thanks

**Comment by Aniket-Engg** [comment]
As title is updated to `Deployed Contracts`. This is no more required. Thanks!

**Pull request closed without merging**
