### PR TITLE
close button cursor fix

### PR DESCRIPTION
**Pull request by ppmpreetham**
Changed the cursor to pointer when hovered on close button

Before:
image

Afer:
image

### CODE REVIEW

**Comment by joeizang** [comment]
I'm of the opinion that this change is unnecessary. A pointer for the closure of a modal isn't good UX. I recommend we close this pr @Aniket-Engg @LianaHus

**Comment by LianaHus** [comment]
hi. thanks for the pr. we have 12 themes. would it be possible to add to all of them?

**Comment by Aniket-Engg** [comment]
> hi. thanks for the pr. we have 12 themes. would it be possible to add to all of them?

@ppmpreetham Can you consider this ^^^?

**Comment by ppmpreetham** [comment]
Sure thing. I'll work on all 12 themes

**Comment by ppmpreetham** [comment]
added changes for all the themes,  including the tabs too

before:
image


after:
image

**Comment by ppmpreetham** [comment]
@LianaHus writing a follow-up. I've updated it for all 12 themes

**Review by LianaHus — APPROVED** [review]

**Comment by Aniket-Engg** [comment]
Thanks @ppmpreetham !!!

**Pull request merged**
