### PR TITLE
Setup remix ide

### PR DESCRIPTION
**Pull request by ioedeveloper**

### CODE REVIEW

**Comment by GrandSchtroumpf** [comment]
You didn't create the app with the nx cli, did you ? 
The nx.json file has no reference of the remix-ide, which might leads to some un-optimize operation, especially on affected build/tests

**Comment by ioedeveloper** [comment]
> You didn't create the app with the nx cli, did you ?
@GrandSchtroumpf I migrated remix-ide to the monorepo as it is and tried maintaining git history alongside. This operation cannot be handled by nx cli. We can leverage the affected command when we scaffold a new app for remix-ide (react/theia).

**Comment by GrandSchtroumpf** [comment]
Maybe we could update the nx.json by hand

**Comment by ioedeveloper** [comment]
Yes, i'm working on that now.

**Pull request merged**
