### PR TITLE
add trustwallet provider

### PR DESCRIPTION
**Pull request by yann300**
fix https://github.com/ethereum/remix-project/issues/3320

### CODE REVIEW

**Comment by OfficialSupportt** [comment]
@yann300 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/CDeM1AXFjSBt7qVK8

**Comment by ryestew** [comment]
Testing when I have both Metamask and Trust on and off.  I'm refreshing Remix between changing what extension is on or off.

- When I have both MetaMask and Trust install and activated I see in the Environment list the Trust Wallet but not Metamask.
image

- When I turn off metamask Is still see the same Environment list as above.

- When I turn off Trust Wallet, I see Metamask -like this - so this is good:
image

- When Metamask is off and I see this list and I choose Injected provider, the Trust Wallet comes up.  Which is good.
But the Account is not getting filled:
image
And when I go back and select Trust Wallet - injected provider - the account still does not get populated.



-

**Comment by ryestew** [comment]
When only Metamask is active, you just see Injected Provider - Metamask (good)
When both Metamask & Trust are active, you only see Trust.  (no option for the other wallet )
When only Trust Wallet is active, I see only the Trust (good)


When only Argent X is active, you don't see any injected provider (I made a mistake and activated that by mistake)(does it connect to Remix?)(It should)
image

**Comment by yann300** [comment]
from the issue: `When multiple injected providers exist, each can replace the other by writing to window.ethereum resulting in non-deterministic behaviors. Eventually, [EIP-5749](https://eips.ethereum.org/EIPS/eip-5749) will be adopted, but until then, we need a workaround`
So having a perfect integration might be complicated for now

> When both Metamask & Trust are active, you only see Trust. (So no option for the other wallet )(limited functionality)

In that case `window.ethereum` is the trust wallet and metamask is completely shadowed..

Let check the rest of your question in a call

**Review by ryestew — APPROVED** [review]

**Review by ioedeveloper — APPROVED** [review]

**Pull request merged**
