### PR TITLE
Update networks.ts

### PR DESCRIPTION
**Pull request by coolestowl**
etherscan api replace goerli with holesky

### CODE REVIEW

**Review by yann300 — APPROVED** [review]

**Comment by coolestowl** [comment]
I'm a little confused. In the setupMetamask step in the test, after typing the words when importing the wallet, it waits to click the confirm button until it times out. Guessing there is some error that is causing the button not to be activated, what should I do to make this pull request pass the test?

**Comment by coolestowl** [comment]
sorry to interrupt, but could you please take a look at this? I tried several times and the same test always fails. @yann300

**Comment by yann300** [comment]
issue with this test is that the CI doesn't seem to push the metamask env correctly. but other tests are fine.

**Comment by coolestowl** [comment]
well, now that we know why, what can I do next to move forward with this pr ?

**Pull request merged**
