### PR TITLE
Solved Undeclared EVM Logs aren't shown in receipt UI #4929

### PR DESCRIPTION
**Pull request by shubhiscoding**
Undeclared EVM Logs are visible now! solved #4929 

Screenshot from 2024-07-06 01-16-33

### CODE REVIEW

**Comment by yann300** [comment]
Thanks for this PR!
it seems you are not showing declared logs if there are undeclared logs, right?
see `JSON.stringify(opts.logs.raw, null, 2)?( <pre>{JSON.stringify(opts.logs.raw || '0', null, 2)}</pre>):(JSON.stringify(stringified, null, '\t'))`
As we still need to show decoded logs, would it be possible to just add a new row in tx details? this row would show raw logs and the other one wold keep showing decoded logs.
Thanks for the help!

**Comment by shubhiscoding** [comment]
> Thanks for this PR! it seems you are not showing declared logs if there are undeclared logs, right? see `JSON.stringify(opts.logs.raw, null, 2)?( \<pre\>{JSON.stringify(opts.logs.raw || '0', null, 2)}\</pre\>):(JSON.stringify(stringified, null, '\t'))` As we still need to show decoded logs, would it be possible to just add a new row in tx details? this row would show raw logs and the other one wold keep showing decoded logs. Thanks for the help!

Screenshot from 2024-07-08 23-30-21
is this fine?

**Comment by yann300** [comment]
ok sorry I should have detailed this more.
Could you put `logs` as before and `raw logs`.
Also please could you remove the changes in the package.json. thanks.

**Comment by shubhiscoding** [comment]
Made logs as it was before and changed undeclared logs as raw logs

Screenshot from 2024-07-09 01-47-21
also reverted changes in package.json
Sorry for changes in package.json, I should have reviewed commit before pushing.

**Review by yann300 — APPROVED** [review]

**Pull request merged**
