### PR TITLE
Monaco editor version update

### PR DESCRIPTION
**Pull request by Aniket-Engg**

### CODE REVIEW

**Comment by LianaHus** [comment]
- there is a border on selected line in editor

**Comment by Aniket-Engg** [comment]
> * there is a border on selected line in editor
> * greater/less symbols have red color
>   Frame 7 (2)

These are default changes done in the newer version

**Comment by LianaHus** [comment]
> > * there is a border on selected line in editor
> > * greater/less symbols have red color
> >   Frame 7 (2)
> 
> These are default changes done in the newer version

ok but this should be fixed. we can discuss <> but selected line looks ugly

**Review by LianaHus — CHANGES_REQUESTED** [review]
As discussed in the chat, please restore the current(live) style of the selected line. If you still suggest changing it, we can discuss it on the UX call.

**Review by LianaHus — APPROVED** [review]

**Pull request merged**
