### PR TITLE
Update run-tab.css

### PR DESCRIPTION
**Pull request by ranjansmygit**
Addressing the UX open issue.
function name got sliced in Udapp #3767

### CODE REVIEW

**Comment by Aniket-Engg** [comment]
@joeizang @LianaHus Please decide for this PR

**Comment by joeizang** [comment]
I think we can close this. I think this was addressed by you @Aniket-Engg right?

**Comment by Aniket-Engg** [comment]
> I think we can close this. I think this was addressed by you @Aniket-Engg right?

I am not sure

**Comment by LianaHus** [comment]
This issue was fixed by adding tooltips and ellipses as we can't use too big space here for buttons. 
thanks for the PR, but I need to close it.

**Pull request closed without merging**
