### PR TITLE
Fading the bg for modals

### PR DESCRIPTION
**Pull request by LianaHus**
fix https://github.com/ethereum/remix-project/issues/425
fix https://github.com/ethereum/remix-project/issues/218

### CODE REVIEW

**Comment by ioedeveloper** [comment]
Modal dialog does not fade out after clicking the faded background area. (e.g publish to IPFS modal, sign message modal)

**Comment by LianaHus** [comment]
> Modal dialog does not fade out after clicking the faded background area. (e.g publish to IPFS modal, sign message modal)

David, I rechecked and it works for me. could you please check again and say with one exactly is not working?

**Review by ryestew — APPROVED** [review]
It worked for me.

**Comment by ioedeveloper** [comment]
It works now for me.

**Review by ioedeveloper — APPROVED** [review]

**Pull request merged**
