### PR TITLE
AI required to support markdown

### PR DESCRIPTION
**Pull request by iamsethsamuel**
So I noticed the AI writes all the codes in plain text thereby make *nlux/react* not able to highlight code properly 

Screenshot 2024-11-26 at 12 47 05

So I added a prompt at the end to ensure the code is properly formated in markdown

image

### CODE REVIEW

**Comment by STetsing** [comment]
Code snippets in the chatbox should be in a markdown format. I adding that prompt enforce the llm more to produce such, good

**Review by STetsing — APPROVED** [review]

**Comment by iamsethsamuel** [comment]
> Seems like [STetsing](https://github.com/STetsing) isn’t online to review the PR

Ohhh. I tried it severally and it wasn't formatting it properly. I posted a screenshot above

**Comment by STetsing** [comment]
@iamsethsamuel how did you try it? You have to wait until the end of streaming

**Comment by iamsethsamuel** [comment]
> @iamsethsamuel how did you try it? You have to wait until the end of streaming

Yes sir, I did

**Comment by STetsing** [comment]
Markdown is already available, 
can't reproduce the scenario/issue in the image above, since not related to prompt engineering. Something else might be the cause

**Comment by iamsethsamuel** [comment]
> Markdown is already available, can't reproduce the scenario/issue in the image above, since not related to prompt engineering. Something else might be the cause

Yeah

**Review by STetsing — COMMENTED** [review]
Markdown is already available, LLM chars Misalignment suspected when starting with markdown

**Comment by STetsing** [comment]
@Aniket-Engg this must be reverted, it causes all prompts to be weird formatted

**Pull request merged**
