### PR TITLE
download folder from FE

### PR DESCRIPTION
**Pull request by Aniket-Engg**
part of #413 

It allows to download a folder in zip format, by right clicking on folder name

### CODE REVIEW

**Comment by yann300** [comment]
could be nice to have a way to download the root folder as zip.

**Comment by ryestew** [comment]
Currently the Download link in the hamburger is for downloading all workspaces.  The label there should probably be updated to "Download All Workspaces" (I'll make an issue)  But then, should the **download workspace** link go in this FE context menu or in the Hamburger menu?  

If we can organize these context menu links so there are not too many - e.g. having sub menus - then I think it should go here.  Otherwise, the link to **download current workspace** could go in the hamburger.

**Comment by yann300** [comment]
LGTM!

**Comment by vermouth22** [comment]
On testing, this is behaving strangely. On right-click of a folder, it will display context menu and download successfully as a straight .zip of the folder. However, attempting to download other folders in the same Workspace or other Workspaces afterwards does not work. I have to reload the entire site to have the context menu display again for download.

**Pull request merged**
