### PR TITLE
Adding metadata save on each compile

### PR DESCRIPTION
**Pull request by edisinovcic**
On each compile save metadata.json file to artifacts.

### CODE REVIEW

**Comment by yann300** [comment]
This will help fixing https://github.com/ethereum/remix-project/issues/72 .
Basically sourcify won't need to store the metadata in its plugin, but the metadata will be store in remix directly.
FYI we already store an artifact file (JSON) which contain another information (bytecode,...), in this PR we are saving exactly what the compiler outputs.
this also means that now we store 2 files for each compiled contracts.
 - <contractname>.json : contains gas estimation, bytecode, sourcemaps,...
 - <contractname>_metadata.json the actual compiler metada output

**Review by ioedeveloper — APPROVED** [review]

**Comment by edisinovcic** [comment]
If everything is good @ioedeveloper @yann300 feel free to merge.

**Comment by yann300** [comment]
@edisinovcic ok, could you just remove the remaining `console.log`

**Comment by edisinovcic** [comment]
@yann300 solved.

**Review by ioedeveloper — APPROVED** [review]

**Pull request merged**
