### PR TITLE
close files on folder close

### PR DESCRIPTION
**Pull request by LianaHus**
fix https://github.com/ethereum/remix-project/issues/1256

should also fix https://github.com/ethereum/remix-project/issues/1259

### CODE REVIEW

**Review by ioedeveloper — APPROVED** [review]

**Review by Aniket-Engg — COMMENTED** [review]
It is not closing tabs neither deleting directory from remix IDE side. It deletes it on remixd side from local fs

on reloading, folder is back locally and remixd both the side with less files

**Comment by bunsenstraat** [comment]
fails on:
connect localhost
open file in nested folder in IDE
delete first parent folder
it will throw an error and the file won't be closed and folder not deleted

**Review by bunsenstraat — CHANGES_REQUESTED** [review]
needs fixing, see comments

**Review by Aniket-Engg — APPROVED** [review]
looks fine to me

**Review by bunsenstraat — APPROVED** [review]

**Pull request merged**
