### PR TITLE
Handle url param

### PR DESCRIPTION
**Pull request by yann300**
fix https://github.com/ethereum/remix-project/issues/1338

### CODE REVIEW

**Review by Aniket-Engg — COMMENTED** [review]
Can you please add e2e tests for this?

Also, with this implementation, if `code` and `url` both are in params,  I am not sure if file with `code` param will be created.

**Comment by yann300** [comment]
>  I am not sure if file with code param will be created.

this should be created but filemanager won't switch to it.

**Review by Aniket-Engg — COMMENTED** [review]
This would be great if you can add an e2e with `code` and `url` both fields at once in URL

**Comment by yann300** [comment]
in order to do manual testing:
- load http://127.0.0.1:8080/#optimize=true&runs=300&evmVersion=istanbul&version=soljson-v0.7.4+commit.3f05b770.js&url=https://github.com/ethereum/remix-project/blob/master/apps/remix-ide/contracts/app/solidity/mode.sol
- make sure `mode.sol` is loaded and switched to.

**Review by Aniket-Engg — APPROVED** [review]
This looks fine now.

Just to add, no matter in which sequence `code` and `url` are assigned in URL, when both are in URL, editor will always open the file from `url` param

**Pull request merged**
