### PR TITLE
Added Option in Dropdown (muirGlacier)

### LINKED ISSUE #865: Add 'muirGlacier' in the list of EVM version in solidity compiler

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #865

### CODE REVIEW

**Review by LianaHus — APPROVED** [review]

**Review by Aniket-Engg — CHANGES_REQUESTED** [review]
As per the sequence used, `muirGlacier` should be the above to `istanbul`

**Comment by Patil2099** [comment]
I have made the changes @Aniket-Engg. Please have a look whenever you are free.

**Comment by Aniket-Engg** [comment]
Thanks @Patil2099, Can you please rebase it?

**Comment by Patil2099** [comment]
@Aniket-Engg Done

**Review by Aniket-Engg — APPROVED** [review]

**Pull request merged**
