### PR TITLE
fixing at address ux

### PR DESCRIPTION
**Pull request by LianaHus**
fix https://github.com/ethereum/remix-project/issues/2573

### CODE REVIEW

**Review by Aniket-Engg — COMMENTED** [review]
I think `"" !== atAddressValue.current.value` will look better in reverse

**Comment by LianaHus** [comment]
> I think `"" !== atAddressValue.current.value` will look better in reverse

**Comment by LianaHus** [comment]
> I think `"" !== atAddressValue.current.value` will look better in reverse

The order doesn't matter, no?

**Review by Aniket-Engg — APPROVED** [review]

**Comment by Aniket-Engg** [comment]
> > I think `"" !== atAddressValue.current.value` will look better in reverse
> 
> The order doesn't matter, no?

That was a suggestion. I don't usually see it like that. Anyway I approved it.

**Review by ryestew — APPROVED** [review]

**Review by joeizang — APPROVED** [review]

**Pull request merged**
