### PR TITLE
Move compilation details to Main panel plugin

### PR DESCRIPTION
**Pull request by joeizang**

### CODE REVIEW

**Review by ryestew — CHANGES_REQUESTED** [review]
This is great!  It just needs a few fixes:
- [ ] The carets disappear in the down state - see image below
- [ ] In ? do the same thing as the carets - is that correct - if so they should be removed.
- [ ] Click on bytecode and there is a lot of stuff - but it is not changing the right side scroll bar (which should be much much longer)(horizontal scroll does not reflect the contents either):
image

**Comment by joeizang** [comment]
> This is great! It just needs a few fixes:
> 
> * [ ]  The carets disappear in the down state - see image below
> * [ ]  In ? do the same thing as the carets - is that correct - if so they should be removed.
> * [ ]  Click on bytecode and there is a lot of stuff - but it is not changing the right side scroll bar (which should be much much longer)(horizontal scroll does not reflect the contents either):
> 
> image

- 1. The carets always disappeared and is the default behaviour.
- 2. This is also the default behaviour. Maybe we keep this default behaviour and propose new behaviour for another pr?
- 3. I am not sure but will try and wrap that and see how it looks.

**Comment by ryestew** [comment]
If it is the default behavior, then lets merge this and fix in another PR (which could be in the next release).

**Comment by joeizang** [comment]
> If it is the default behavior, then lets merge this and fix in another PR (which could be in the next release).

You will need to approve this. 😄

**Comment by yann300** [comment]
just a thought, maybe the some of the important section could be unfolded by default...

**Review by ryestew — APPROVED** [review]

**Pull request merged**
