### PR TITLE
download contract compilation details

### PR DESCRIPTION
**Pull request by Aniket-Engg**
related to #413 

This shows option to download compilation details on modal showing details.

On clicking on `Download` , modal will not close.

### CODE REVIEW

**Comment by yann300** [comment]
there could be 3 options:
 - download compilation details as it is show in the modal
 - download the compilation result (this is the standard output)
 - downloac the compilation input (this is the standard input)

**Comment by Aniket-Engg** [comment]
> there could be 3 options:
> 
> * download compilation details as it is show in the modal
> * download the compilation result (this is the standard output)
> * downloac the compilation input (this is the standard input)

will do it in a separate PR

**Review by yann300 — APPROVED** [review]

**Review by LianaHus — CHANGES_REQUESTED** [review]
i see a small problem here. when we click download modal shouldn't disappear.

**Comment by Aniket-Engg** [comment]
> i see a small problem here. when we click download modal shouldn't disappear.

ok, lets discuss this

**Pull request merged**
