### PR TITLE
Add support for fetching contracts from blockscout instances 

### PR DESCRIPTION
**Pull request by rimrakhimov**
This pr aims to allow to fetch contracts from the blockscout instances. In doing so, it requires the following url params:
`/#address={contract_address}&blockscout={blockscout_domain}` (e.g., `#address=0xdAC17F958D2ee523a2206206994597C13D831ec7&blockscout=eth.blockscout.com`)

### CODE REVIEW

**Comment by rimrakhimov** [comment]
@Aniket-Engg @LianaHus @yann300 Is there any used workflow what should be done in order for the PR to be considered? I'll resolve the conflicts if that make sense, but would be happy to get any kind of feedback

**Comment by Aniket-Engg** [comment]
Hello @rimrakhimov , Thanks for the PR. We are in discussion to come up with the ways to support more explorers in general. Will update you soon on this.

**Comment by Aniket-Engg** [comment]
cc: @ryestew

**Comment by ryestew** [comment]
Apart from this PR,  we'd also like to add blockscan for verifying.  Let's have a call to coordinate.  Please join our discord: https://discord.gg/W7V2yYNz
and/or email: remix@ethereum.org

**Comment by Aniket-Engg** [comment]
> changeset looks fine. Can you please rebase??

@rimrakhimov

**Review by Aniket-Engg — APPROVED** [review]

**Pull request merged**
