### PR TITLE
Search3

### PR DESCRIPTION
**Pull request by bunsenstraat**
- use enter to search/also on include/exclude, do not update on typing
- search can be stopped with a stop button
- async plugin calls to files are canceled when search params changes
- search is throttled so not all files get hit one after another, so there is a delay between files
- file names that are searched are being displayed

### CODE REVIEW

**Comment by yann300** [comment]
@bunsenstraat could you shortly describe how you did approach the changes?

**Comment by bunsenstraat** [comment]
@yann300  fixed
- clear highlights when search changes
- bug : when cloning it didn't index the files

**Comment by LianaHus** [comment]
could you please add some spacing at the bottom of search result

**Comment by bunsenstraat** [comment]
> could you please add some spacing at the bottom of search result

Where exactly and how much?

**Comment by LianaHus** [comment]
`pb-4` to search_plugin_search_tab :)

**Review by yann300 — APPROVED** [review]

**Pull request merged**
